# Generated by Django 5.0.6 on 2026-03-31 00:00

from django.db import migrations, models
import planner.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlannerWorkspaceState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enrollment_closed", models.BooleanField(default=False)),
                ("participants", models.JSONField(default=list)),
                ("teams", models.JSONField(default=list)),
                ("parent_tasks", models.JSONField(default=list)),
                ("subtasks", models.JSONField(default=list)),
                ("columns", models.JSONField(default=planner.models.planner_default_columns)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "CRM_PLANNER_WORKSPACE_STATE",
            },
        ),
        migrations.CreateModel(
            name="TeamPlannerDesk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("team_id", models.BigIntegerField(unique=True)),
                ("team_name", models.CharField(blank=True, max_length=255)),
                ("curator_id", models.BigIntegerField(blank=True, null=True)),
                ("member_ids", models.JSONField(default=list)),
                ("parent_tasks", models.JSONField(default=list)),
                ("subtasks", models.JSONField(default=list)),
                ("columns", models.JSONField(default=planner.models.planner_default_columns)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "CRM_TEAM_PLANNER_DESK",
                "ordering": ("team_id",),
            },
        ),
    ]
