# Generated by Django 4.1 on 2026-05-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_planner_automation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='plannerautomationexecutionlog',
            new_name='CRM_PLANNER_event_i_272550_idx',
            old_name='CRM_PLANN_event_i_56b711_idx',
        ),
        migrations.RenameIndex(
            model_name='plannerautomationexecutionlog',
            new_name='CRM_PLANNER_schedul_bb2a14_idx',
            old_name='CRM_PLANN_schedul_51505a_idx',
        ),
    ]
