from django.urls import path

from .views import (
    ApplicationDetailView,
    ApplicationListView,
    CRMAutomationAttachmentListCreateView,
    CRMAutomationConfigView,
    CRMAutomationExecutionLogListView,
    CRMAutomationPendingRunView,
    CookieTokenRefreshView,
    DirectionApplicationCreateView,
    DirectionDetailView,
    DirectionListCreateView,
    EmailConfirmationView,
    EventDetailView,
    EventDetailsExportView,
    EventApplicationsExportView,
    EventListCreateView,
    IntegrationApplicationTestingContextView,
    IntegrationApplicationStatusView,
    IntegrationApplicationTestResultView,
    IntegrationApplicationTestSessionView,
    IntegrationTestExportView,
    TestingSSOExchangeView,
    TestingSSOLinkView,
    LoginView,
    LogoutView,
    NotificationClearView,
    NotificationDetailView,
    NotificationListCreateView,
    NotificationMarkAllReadView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    ProjectDetailView,
    ProjectListCreateView,
    SpecializationListView,
    StatusListView,
    ProfileView,
    UserInfoView,
    UserRegistrationView,
    UserDirectionListView,
    UserListView,
    UserProjectListCreateView,
)

urlpatterns = [
    path("", UserListView.as_view(), name="user-list"),
    path("user-info/", UserInfoView.as_view(), name="user-info"),
    path("register/", UserRegistrationView.as_view(), name="registration"),
    path("login/", LoginView.as_view(), name="user-login"),
    path("logout/", LogoutView.as_view(), name="user-logout"),
    path("refresh/", CookieTokenRefreshView.as_view(), name="token-refresh"),
    path("password-reset/request/", PasswordResetRequestView.as_view(), name="password-reset-request"),
    path("password-reset/confirm/", PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("confirm-email/", EmailConfirmationView.as_view(), name="email-confirmation"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("events/", EventListCreateView.as_view(), name="event-list-create"),
    path("events/<int:event_id>/", EventDetailView.as_view(), name="event-detail"),
    path(
        "events/<int:event_id>/export/details.docx/",
        EventDetailsExportView.as_view(),
        name="event-export-details-docx",
    ),
    path(
        "events/<int:event_id>/export/applications.xlsx/",
        EventApplicationsExportView.as_view(),
        name="event-export-applications-xlsx",
    ),
    path(
        "events/<int:event_id>/directions/",
        DirectionListCreateView.as_view(),
        name="direction-list-create",
    ),
    path(
        "events/<int:event_id>/directions/<int:direction_id>/",
        DirectionDetailView.as_view(),
        name="direction-detail",
    ),
    path(
        "events/<int:event_id>/directions/<int:direction_id>/applications/",
        DirectionApplicationCreateView.as_view(),
        name="direction-application-create",
    ),
        path(
        "events/<int:event_id>/directions/<int:direction_id>/projects/",
        ProjectListCreateView.as_view(),
        name="project-list-create",
    ),
    path(
        "projects/<int:project_id>/",
        ProjectDetailView.as_view(),
        name="project-detail",
    ),
    path("projects/", UserProjectListCreateView.as_view(), name="user-project-list-create"),
    path("directions/", UserDirectionListView.as_view(), name="user-direction-list"),
    path("applications/", ApplicationListView.as_view(), name="application-list"),
    path(
        "applications/<int:application_id>/",
        ApplicationDetailView.as_view(),
        name="application-detail",
    ),
    path("automation/<int:event_id>/", CRMAutomationConfigView.as_view(), name="crm-automation-config"),
    path(
        "automation/<int:event_id>/attachments/",
        CRMAutomationAttachmentListCreateView.as_view(),
        name="crm-automation-attachment-list",
    ),
    path(
        "automation/<int:event_id>/logs/",
        CRMAutomationExecutionLogListView.as_view(),
        name="crm-automation-log-list",
    ),
    path("automation/run-pending/", CRMAutomationPendingRunView.as_view(), name="crm-automation-run-pending"),
    path(
        "integration/applications/<int:application_id>/testing-context/",
        IntegrationApplicationTestingContextView.as_view(),
        name="integration-application-testing-context",
    ),
    path(
        "integration/testing/sso-link/",
        TestingSSOLinkView.as_view(),
        name="integration-testing-sso-link",
    ),
    path(
        "integration/testing/sso-exchange/",
        TestingSSOExchangeView.as_view(),
        name="integration-testing-sso-exchange",
    ),
    path(
        "integration/applications/<int:application_id>/test-sessions/",
        IntegrationApplicationTestSessionView.as_view(),
        name="integration-application-test-session",
    ),
    path(
        "integration/applications/<int:application_id>/test-results/",
        IntegrationApplicationTestResultView.as_view(),
        name="integration-application-test-result",
    ),
    path(
        "integration/applications/<int:application_id>/status/",
        IntegrationApplicationStatusView.as_view(),
        name="integration-application-status",
    ),
    path(
        "integration/tests/<int:test_id>/export/",
        IntegrationTestExportView.as_view(),
        name="integration-test-export",
    ),
    path("notifications/", NotificationListCreateView.as_view(), name="notification-list"),
    path(
        "notifications/<int:notification_id>/",
        NotificationDetailView.as_view(),
        name="notification-detail",
    ),
    path(
        "notifications/mark-all-read/",
        NotificationMarkAllReadView.as_view(),
        name="notification-mark-all-read",
    ),
    path(
        "notifications/clear/",
        NotificationClearView.as_view(),
        name="notification-clear",
    ),
    path("statuses/", StatusListView.as_view(), name="status-list"),
    path(
        "specializations/", SpecializationListView.as_view(), name="specialization-list"
    ),
]
