# Generated by Django 5.0.6 on 2025-12-16 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('stage', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('end_app_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'CRM_EVENT',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='crm_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('surname', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('patronymic', models.CharField(blank=True, max_length=150)),
                ('telegram', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.PositiveIntegerField()),
                ('university', models.CharField(blank=True, max_length=255)),
                ('vk', models.CharField(blank=True, max_length=255)),
                ('job', models.CharField(blank=True, max_length=255)),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_token_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CRM_PROFILE',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('count', models.IntegerField()),
                ('points', models.IntegerField()),
                ('question_type', models.CharField(choices=[('single', 'Один вариант'), ('multi', 'Несколько вариантов'), ('text', 'Текстовый ответ')], max_length=50)),
            ],
            options={
                'db_table': 'CRM_QUESTION',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'CRM_SPECIALIZATION',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_positive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'CRM_STATUS',
            },
        ),
        migrations.CreateModel(
            name='CRMRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('admin', 'Админ'), ('curator', 'Куратор'), ('projectant', 'Проектант')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CRM_ROLE',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_directions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='users.event')),
            ],
            options={
                'db_table': 'CRM_DIRECTION',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('tg', 'Telegram'), ('vk', 'VK')], max_length=50)),
                ('data', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='users.profile')),
            ],
            options={
                'db_table': 'CRM_CONTACT',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('is_selected', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.question')),
            ],
            options={
                'db_table': 'CRM_ANSWER',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.specialization'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('is_link', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('date_sub', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('project_id', models.BigIntegerField(blank=True, null=True)),
                ('team_id', models.BigIntegerField(blank=True, null=True)),
                ('tests_assigned', models.BooleanField(default=False)),
                ('tests_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('test_session_id', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='users.direction')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='users.event')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='users.specialization')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='users.status')),
            ],
            options={
                'db_table': 'CRM_APPLICATION',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entry', models.IntegerField()),
                ('passing_score', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('question_count', models.IntegerField()),
                ('test_type', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн')], max_length=50)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='users.event')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='users.specialization')),
            ],
            options={
                'db_table': 'CRM_TEST',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.test'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('is_passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField()),
                ('started_at', models.DateTimeField()),
                ('correct_answers', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_spent_seconds', models.IntegerField()),
                ('result_status', models.CharField(max_length=100)),
                ('detailed_results', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='users.application')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CRM_TEST_RESULT',
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('answers_data', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='users.application')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CRM_TEST_SESSION',
            },
        ),
        migrations.CreateModel(
            name='TrueAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('true_answer', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_answers', to='users.question')),
            ],
            options={
                'db_table': 'CRM_TRUE_ANSWER',
            },
        ),
        migrations.CreateModel(
            name='EventSpecialization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_specializations', to='users.event')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_specializations', to='users.specialization')),
            ],
            options={
                'db_table': 'CRM_EVENT_SPECIALIZATIONS',
                'unique_together': {('event', 'specialization')},
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('direction__isnull', False)), fields=('user', 'direction'), name='unique_application_per_direction'),
        ),
    ]
