# Generated by Django 5.0.6 on 2026-03-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_application_project_id_alter_profile_course_and_more'),
    ]

    operations = []
