# Generated by Django 5.0.6 on 2026-04-22 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_alter_eventspecialization_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="specialty",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="workplace",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
