# Generated by Django 4.1 on 2026-05-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_removed_from_psh_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMAutomationConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope', models.CharField(default='crm', max_length=32)),
                ('stages', models.JSONField(default=list)),
                ('triggers', models.JSONField(default=list)),
                ('robots', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_automation_configs', to='users.event')),
            ],
            options={
                'db_table': 'CRM_AUTOMATION_CONFIG',
            },
        ),
        migrations.CreateModel(
            name='CRMAutomationExecutionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.BigIntegerField()),
                ('entity_type', models.CharField(default='application', max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('event_code', models.CharField(max_length=100)),
                ('rule_kind', models.CharField(max_length=16)),
                ('rule_id', models.CharField(max_length=120)),
                ('run_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('context', models.JSONField(default=dict)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='users.application')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='users.crmautomationconfig')),
            ],
            options={
                'db_table': 'CRM_AUTOMATION_EXECUTION_LOG',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='crmautomationexecutionlog',
            index=models.Index(fields=['event_id', 'created_at'], name='CRM_AUTOMAT_event_i_eebf14_idx'),
        ),
        migrations.AddIndex(
            model_name='crmautomationexecutionlog',
            index=models.Index(fields=['scheduled_for', 'status'], name='CRM_AUTOMAT_schedul_88eb53_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmautomationconfig',
            constraint=models.UniqueConstraint(fields=('scope', 'event'), name='unique_crm_automation_config_scope_event'),
        ),
    ]
